---
title: "Project 1 Main"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(httr)
```

### 311 data

```{r include=FALSE}
api_key <- "1x1syxa046asdu0rkk842sht5"
api_key_secret <- "3y8qpo8krd82vwnhxxjufuk8fv35tidgvc0gx2dhnbgeor1900"
token <- "ADRRlI3DDJge67NUzvmCG3vU3"
```

```{r}
#sample pull of 1 entry
#https://data.cityofnewyork.us/resource/erm2-nwe9.json?unique_key=10693408
```


```{r}
## Install the required package with:
## install.packages("RSocrata")

library("RSocrata")

#df <- ls.socrata("http://data.cityofnewyork.us")

df <- read.socrata(url = "https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=10")

df
```


```{r}
#Data were loaded into RStudio via the RSocrata library using the following code. 

#Install RSocrata library 
library(RSocrata) 

# Call in NYC data for 2019
nyc <-  as.data.frame(read.socrata("https://data.cityofnewyork.us/resource/fhrw-4uyv.json?$where=created_date between '2019-01-01T12:00:00' and '2019-12-31T23:59:59'", app_token = token))

#nyc

```



