---
title: "Project 1 Main"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#general
library(tidyverse)
library(httr)
#for 311 data
library("RSocrata")

#pulling data
library(jsonlite)

#mapping libraries
library(tigris)
library(leaflet)
library(sp)
library(ggmap)
library(maptools)
library(broom)
library(rgdal)
library(lubridate)
```

### 311 data

```{r API info, include=FALSE}
api_key <- "1x1syxa046asdu0rkk842sht5"
api_key_secret <- "3y8qpo8krd82vwnhxxjufuk8fv35tidgvc0gx2dhnbgeor1900"
token <- "ADRRlI3DDJge67NUzvmCG3vU3"
```


```{r Sample Data Pulls, eval=FALSE, include=FALSE}
#sample pull of 1 entry
#https://data.cityofnewyork.us/resource/erm2-nwe9.json?unique_key=10693408

#sample pull of 10
#df <- read.socrata(url = "https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=10")
```

```{r 311 data pull}

# Call in NYC data for 2019
nyc <-  as_tibble(read.socrata("https://data.cityofnewyork.us/resource/fhrw-4uyv.json?$where=created_date between '2018-01-01T12:00:00' and '2018-12-31T23:59:59' and agency = 'NYPD'", app_token = token))

#head(nyc)

#clean the data
df_311 <- nyc %>% 
  mutate_at(vars(incident_zip, latitude, longitude, location_zip), as.numeric)
  
#summary(df_311)
```




### Salary Data

```{r}
#select only 1 year
url_2018 <- "https://data.cityofnewyork.us/resource/k397-673e.json?fiscal_year=2019"

#create dataframe of payroll
df_payroll <- as_tibble(read.socrata(url_2018))

df_payroll_cleaned <- df_payroll %>%
  mutate_at(vars(fiscal_year,
         payroll_number,
         base_salary,
         ot_hours,
         total_ot_paid,
         total_other_pay), as.numeric) 

```

```{r eval=FALSE, include=FALSE}
summary(df_payroll_cleaned)

factor(df_payroll_cleaned$agency_name)
```



```{r warning=FALSE}
class(df_payroll_cleaned$agency_start_date)

ggplot(df_payroll_cleaned, aes(x = year(agency_start_date))) + 
  geom_histogram(binwidth = 1) + 
  xlim(1960,2021)

```


### Exploring the data

```{r}
#head(df_311)

counts_of_start_type <- df_311 %>% 
  group_by(open_data_channel_type) %>% 
  summarize(number_rows = n())
```

```{r}
ggplot(counts_of_start_type, aes(x = "", y = number_rows, fill = open_data_channel_type)) + 
  geom_bar(stat = "identity", width = 1, color="white") + 
  coord_polar("y", start = 0) + 
  theme_void() # remove background, grid, numeric labels
```



### Mapping of the data

```{r}
register_google(key = "AIzaSyAEkvFUTrN-n96QqRvpHxmtNyucQveP8oU")
```

 
```{r}
nyc_map <- get_map(location = c(lon = -74.00, lat = 40.71), maptype = "terrain", zoom = 11)
```


```{r}
ggmap(nyc_map)
```



```{r}
leaflet() %>%
  addTiles() %>%
  setView(-74.00, 40.71, zoom = 12)
```
```


